---
- name: User
  hosts: cluster
  tasks:
    - name: Preconfig block
      become: true
      block:
        - name: Reboot
          ansible.builtin.shell: "sleep 2 && reboot"
          async: 1000
          poll: 0
          changed_when: false
