---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: Reboot
          shell: "sleep 2 && reboot"
          async: 1000
          poll: 0
      become: true

